idxbroker/wordpress-plugin

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
To further define the collaboration experience here on github for this project I have created the following documents. 
* Contributing.md
* Code of Coduct.md
* LICENSE.md
* Issue template
* pull request template
This should close #78
> Create basic documents

- idx/idx-pages.php
- idx/shortcodes/shortcode-ui.php
- idx/views/lead-management.php
- idx/views/omnibar-settings.php
- idx/views/search-management.php
- idx/wrappers.php
Updated Select2 to version 4.05. In the future we should just register it in one place and then enqueue it when needed.
> Update Select2 to version 4.0.5

- idx/backward-compatibility/add-uid-to-idx-pages.php
- idx/backward-compatibility/legacy-functions.php
- idx/backward-compatibility/migrate-legacy-widgets.php
- idx/backward-compatibility/migrate-old-table.php
Focused on just the Backwards Compatibility Directory.
> Lots of PHP Standard Fixes for Backwards Compatibility Directory

- idx/backward-compatibility/add-uid-to-idx-pages.php
- idx/backward-compatibility/legacy-functions.php
- idx/backward-compatibility/migrate-legacy-widgets.php
- idx/backward-compatibility/migrate-old-table.php
Fixes errors introduced in #86
> Fix namespace errors

- idx/idx-api.php
Hides the upgrade option for accounts that are already Platinum.
> Fix for new account type string

- README.md
- idx-broker-platinum.php
- idx/initiate-plugin.php
- readme.txt
Reverts idxbroker/wordpress-plugin#119
> Revert "Version number incremented, readme updated, and gutenberg blocks hidden"

- README.md
- idx-broker-platinum.php
- idx/initiate-plugin.php
- idx/widgets/omnibar/create-omnibar.php
- readme.txt
Updated readme, version number and tested version bumped.
> Release 2.5.11 v2

- idx/shortcodes/register-impress-shortcodes.php
Removal of arrow function as it was causing errors in IE11.
> IE11 Arrow Function Issue

- idx/help.php
- idx/initiate-plugin.php
- idx/views/admin.php
Links changed:
/mgmt/**apikey.php** -> /mgmt/**access-control**
/mgmt/**login.php** -> /mgmt/**login**
> Updated links to IDX Broker pages

- idx/idx-api.php
- idx/initiate-plugin.php
Updated default IDXB API version to 1.7.0 and updated functions client_properties(), get_featured_listings(), and get_leads() to make use of the new API version features.
> WP-1015: IDXB API v1.7.0 Changes

- assets/js/idx-leads.js
- idx/views/lead-management.php
Leads table reworked to load data via Ajax.
> WP-1051: Reworked Leads Table

- idx/shortcodes/register-impress-shortcodes.php
- idx/widgets/impress-carousel-widget.php
- Changes made to to carousel widget and shortcode implementation so they match
- Removed old FA4 icons and the FA4 shim
> IMPress Carousel Changes

- idx/notice/notice-handler.php
- Updating link to no-index KB article in notice-handler.php
> Update KB Article Link

- idx/idx-api.php
* Change will allow supplemental listings to be imported when using IMPress Listings
> Changes to client_properties function to handle inclusion of disclaimers

- idx/widgets/omnibar/create-omnibar.php
Step changes for Omnibar extra fields:
Bed and Bath fields: 0.01 -> 1
Min/Max Price fields: 1 -> 10000
> Increased step size for Omnibar extra fields

- README.md
- readme.txt
Both Readme files updated with new pricing info.
> Readme Files Updated with Price Change

- idx/idx-pages.php
* Resolves event scheduling issue that can interfere with other cron tasks
> Fix for event scheduling issue

- idx/idx-api.php
* Added early exit for idx_api requests if API key is missing
> Added check for missing API key

- idx/shortcodes/register-idx-shortcodes.php
- idx/widgets/idx-middleware-widget.php
- Added ID to script tags of IDXB widgets to cover the new Virtual Tours and Market Report widgets that require it
> Added ID to IDXB shortcode widget scripts

- src/vue/backend/src/App.vue
- src/vue/backend/src/components/Feedback.vue
- src/vue/backend/src/main.js
http://jira.hq.idx.org/browse/UXG-1263
> UXG-1263 add warning feedback component

- src/vue/backend/src/router/index.js
UXG-1280 Added the route structure skeleton for the IMPress plugin consolidation.
> UXG-1280: Added Route structure

- src/vue/backend/src/main.js
- src/vue/backend/src/store/modules/listingsSettings/actions.js
- src/vue/backend/src/store/modules/listingsSettings/index.js
- src/vue/backend/src/store/modules/listingsSettings/mutations.js
- src/vue/backend/src/styles/verticalNavBar.scss
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/templates/page.vue
> UXG-1243: IMPress listings IDX Tab

- src/vue/backend/src/store/modules/agentSettings/actions.js
- src/vue/backend/src/store/modules/agentSettings/index.js
- src/vue/backend/src/store/modules/agentSettings/mutations.js
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/ListingsGeneral.vue
http://jira.hq.idx.org/browse/UXG-1246
> UXG-1246: adds agents settings

- src/vue/backend/src/main.js
- src/vue/backend/src/store/common/actions.js
- src/vue/backend/src/store/common/mutations.js
- src/vue/backend/src/store/modules/general/index.js
- src/vue/backend/src/store/modules/listingsSettings/index.js
- src/vue/backend/src/store/modules/omnibar/actions.js
- src/vue/backend/src/store/modules/omnibar/index.js
- src/vue/backend/src/store/modules/omnibar/mutations.js
- src/vue/backend/src/styles/formContentStyles.scss
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/ListingsGeneral.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/templates/socialProForm.vue
UXG-1240, adds omnibar form as well as adds a common form css file. Made adjustments to other files to add the common css, made adjustments to the custom select implementation to match the updated custom select component
> UXG-1240: Omnibar form

- src/vue/backend/src/store/modules/listingsSettings/index.js
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/ListingsAdvanced.vue
http://jira.hq.idx.org/browse/UXG-1244
> UXG-1244: adds advanced listing settings tab content

- idx/admin/apis/settings-general.php
- idx/admin/rest-controller.php
- idx/idx-api.php
- idx/initiate-plugin.php
- idx/wrappers.php
Adds REST endpoints for the general settings page.
Adds new interface to update settings on the upcoming general/settings page. Rips out existing AJAX endpoint code and puts it into the REST controller instead as the AJAX code is no longer used.
> WP-1283: Added admin rest API interface and general settings POST/GET

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/components/ContentCard.vue
- src/vue/backend/src/styles/formContentStyles.scss
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/ListingsGeneral.vue
- src/vue/backend/src/templates/layout/TwoColumn.vue
- src/vue/backend/src/views/GuidedSetupConnectApi.vue
- src/vue/backend/src/views/settings/General.vue
http://jira.hq.idx.org/browse/UXG-1235
> UXG-1235: general settings page

- idx/admin/apis/agents-settings.php
- idx/admin/apis/settings-general.php
- idx/admin/rest-controller.php
Adds Agents Settings API and adds more robust POST validation to existing endpoints.
> WP-1290: Adds agents settings API and more route validation

- add-ons/listings/includes/listing-templates/single-listing-classical.php
- add-ons/listings/includes/listing-templates/single-listing-elegant.php
- add-ons/listings/includes/listing-templates/single-listing-luxurious.php
- add-ons/listings/includes/listing-templates/single-listing-solid.php
- add-ons/listings/includes/listing-templates/single-listing-spacious.php
- add-ons/listings/includes/views/single-listing.php
- src/scss/wp-listings-single.scss
* Copied over recaptcha changes to the custom listing templates
* Cleaned up script enqueuing and excluded a conflicting stylesheet
> Updates to Listing Templates

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/store/index.js
- src/vue/backend/src/store/modules/agentSettings/actions.js
- src/vue/backend/src/store/modules/agentSettings/index.js
- src/vue/backend/src/store/modules/agentSettings/mutations.js
- src/vue/backend/src/store/modules/general/actions.js
- src/vue/backend/src/store/modules/general/index.js
- src/vue/backend/src/store/modules/general/mutations.js
- src/vue/backend/src/store/modules/listingsSettings/actions.js
- src/vue/backend/src/store/modules/listingsSettings/index.js
- src/vue/backend/src/store/modules/listingsSettings/mutations.js
- src/vue/backend/src/store/modules/omnibar/actions.js
- src/vue/backend/src/store/modules/omnibar/index.js
- src/vue/backend/src/store/modules/omnibar/mutations.js
- src/vue/backend/src/store/modules/progressStepper/actions.js
- src/vue/backend/src/store/modules/progressStepper/index.js
- src/vue/backend/src/store/modules/socialPro/actions.js
- src/vue/backend/src/store/modules/socialPro/index.js
- src/vue/backend/src/store/modules/socialPro/mutations.js
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/ListingsGeneral.vue
- src/vue/backend/src/templates/impressListingsAdvancedContent.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/General.vue
UXG-1298: Added in the progress stepper state and updated the current views to use it. Also I added in common action/mutation so that there is a single source of truth for those instead of repeated code. Updated the forms to match.
> UXG-1298: Adding common actions and mutations with progress stepper

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/components/ContentCard.vue
- src/vue/backend/src/router/routeMeta.js
- src/vue/backend/src/store/modules/listingsSettings/actions.js
- src/vue/backend/src/store/modules/progressStepper/index.js
- src/vue/backend/src/styles/formContentStyles.scss
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/impressListingsAdvancedContent.vue
- src/vue/backend/src/templates/impressListingsGeneralContent.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/children/advancedContentTab.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/General.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/Omnibar.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/Listings.vue
UXG-1302: Updated the forms to no longer be coupled to the state, but instead pass options through props.
> UXG-1302: Decouple overhaul

- src/vue/backend/package.json
- src/vue/backend/src/mixins/pageGuard.js
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/views/children/advancedContentTab.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/General.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/Omnibar.vue
- src/vue/backend/src/views/settings/Agents.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/Omnibar.vue
- src/vue/backend/src/views/settings/SocialPro.vue
UXG-1303 Added page leave guards and updated vies
> UXG-1303: Added page guards and updated forms

- idx/admin/apis/agents-settings.php
- idx/admin/apis/settings-general.php
- idx/admin/rest-controller.php
- idx/idx-api.php
Normalized errors from IDX's API and stripped HTML from the error codes. Also removes unneeded `required` checks for non-required args.
> WP-1300: Normalized errors and removed unnecessary required checks

- src/vue/backend/src/App.vue
- src/vue/backend/src/data/productTerms.js
- src/vue/backend/src/repositories/generic.class.js
- src/vue/backend/src/repositories/listingsSettings.class.js
- src/vue/backend/src/repositories/socialPro.class.js
- src/vue/backend/src/serviceContainer.js
- src/vue/backend/src/store/modules/socialPro/index.js
* Adds some specific product references for reusability
* Injects product repositories in `App.vue`
* Adds initial API call on created hook in `App.vue` using repositories
* Conditionally looks up social pro subscription, pending API key
> WP-1303: Upfront product settings API call + handling.

- src/vue/backend/src/router/index.js
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/ListingsAdvanced.vue
- src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
- src/vue/backend/src/views/guided-setup/Omnibar.vue
http://jira.hq.idx.org/browse/UXG-1274
> UXG-1274 adds listings advanced guided setup page

- src/vue/backend/src/components/BulkAction.vue
- src/vue/backend/src/components/listingsCard.vue
- src/vue/backend/src/mixins/importPages.js
- src/vue/backend/src/router/routeMeta.js
- src/vue/backend/src/store/modules/importContent/index.js
- src/vue/backend/src/views/children/importedListings.vue
- src/vue/backend/src/views/children/unimportedListings.vue
- src/vue/backend/src/views/import/Listings.vue
Added an import page mixin, and added in the implementation for importing and removing listings.
> UXG-1250: Added import/unimport listings

- src/vue/backend/src/store/modules/socialPro/index.js
- src/vue/backend/src/templates/page.vue
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/SocialPro.vue
UXG-1247: Added in the general social pro form
> UXG-1247: social pro form

- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/views/settings/Omnibar.vue
UXG-1239: Added in the general page for omnibar
> UXG-1239: Added omnibar general page

- add-ons/agents/includes/class-agent-import.php
* Removed in_array function as it is just replicating the built-in function (I assume this is some old compatibility holdover)
* Updated to use IDX API v1.7.0
* Simplified import logic to get rid of the hand maintained list to know which agents to import
* Cleaned up file some, this includes removing old array() syntax, removing unused variables, and adding doc comments
> Changes to Agent Import Class

- idx/admin/apis/import-agents.php
- idx/admin/rest-controller.php
* Added agent import rest routes
> Agent Import API

- src/vue/backend/src/components/BulkAction.vue
- src/vue/backend/src/components/agentCard.vue
- src/vue/backend/src/mixins/importPages.js
- src/vue/backend/src/router/routeMeta.js
- src/vue/backend/src/views/children/importedAgents.vue
- src/vue/backend/src/views/children/unimportedAgents.vue
- src/vue/backend/src/views/import/Agents.vue
UXG-1257: agents import and unimporting actions
> UXG-1257: import/unimport agents

- src/vue/backend/src/router/index.js
- src/vue/backend/src/store/modules/agentSettings/actions.js
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/views/guided-setup/AgentsConfigure.vue
http://jira.hq.idx.org/browse/UXG-1276
> UXG-1276 adds agents configure guided setup page

- src/vue/backend/src/router/index.js
- src/vue/backend/src/store/modules/socialPro/actions.js
- src/vue/backend/src/views/guided-setup/SocialPro.vue
http://jira.hq.idx.org/browse/UXG-1277
> UXG-1277 adds activate social pro guided setup page

- idx/admin/apis/listings-settings.php
- idx/admin/rest-controller.php
http://jira.hq.idx.org/browse/IMPB-1285
> Wp 1285 listings general api

- idx/admin/apis/agents-settings.php
- idx/admin/apis/settings-general.php
- idx/admin/rest-controller.php
Converts array() to [] for existing API code
> Impb 1309 convert array syntax

- src/vue/backend/src/router/index.js
- src/vue/backend/src/store/modules/socialPro/actions.js
- src/vue/backend/src/views/guided-setup/SocialProConfigure.vue
http://jira.hq.idx.org/browse/UXG-1278
> UXG-1278 adds configure social pro guided setup page

- src/vue/backend/src/mixins/guidedSetup.js
- src/vue/backend/src/router/index.js
- src/vue/backend/src/store/modules/agentSettings/actions.js
- src/vue/backend/src/store/modules/agentSettings/index.js
- src/vue/backend/src/store/modules/listingsSettings/actions.js
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
http://jira.hq.idx.org/browse/UXG-1275
> UXG-1275 adds activate agents guided setup page

- src/vue/backend/src/styles/globalVariables.scss
- src/vue/backend/src/styles/verticalNavBar.scss
- src/vue/backend/src/templates/navbar.vue
http://jira.hq.idx.org/browse/UXG-1308
> UXG-1308 fixes mobile header gap

- idx/admin/apis/enable-addons.php
- idx/admin/rest-controller.php
Provides a general class to enable/disable addons. Currently supports IMPress Agents and IMPress Listings.
> IMPB-1287: Adds endpoints to enable/disable addons and check their status

- src/vue/backend/src/data/navlinks.js
- src/vue/backend/src/router/index.js
- src/vue/backend/src/views/guided-setup/Welcome.vue
UXG-1304: Updated the welcome screen to match designs and updated the path that it uses in the navigation.
> UXG-1304: Updated welcome screen

- src/vue/backend/src/components/ContentCard.vue
http://jira.hq.idx.org/browse/UXG-1305
> UXG-1305 adds progress stepper complete icon

- add-ons/listings/includes/class-listing-import.php
Cleaned up listing import class, removed old UI/script enqueues and rest routes that are no longer needed along with some other minor tweaks
> Listing Import Class Changes

- idx/admin/apis/import-listings.php
- idx/admin/rest-controller.php
- Added listing import rest routes
> Import Listings API

- src/vue/backend/src/styles/formContentStyles.scss
http://jira.hq.idx.org/browse/UXG-1322
> UXG-1322 updates styles to reflect api state

- idx/admin/apis/agents-settings.php
- idx/admin/apis/import-agents.php
- idx/admin/apis/settings-general.php
- Updated the POST return format on the 3 API files that were created before we started including the 204 status
> Updated POST Return Format

- src/vue/backend/src/components/listingsCard.vue
- src/vue/backend/src/mixins/importPages.js
- src/vue/backend/src/templates/importPageTemplate.vue
- src/vue/backend/src/views/children/importedAgents.vue
- src/vue/backend/src/views/children/importedListings.vue
- src/vue/backend/src/views/children/unimportedAgents.vue
- src/vue/backend/src/views/children/unimportedListings.vue
- src/vue/backend/src/views/import/Agents.vue
- src/vue/backend/src/views/import/Listings.vue
UXG-1318: Updated the import/unimport agents and listings pages to be more DRY
> UXG-1318: Cleaned up implementation

- idx/admin/apis/listings-idx-settings.php
Changed returned options format from [ label => value ] to [ [ value => value, label => label ] ] as per request
> Returned Options Format Changes

- src/vue/backend/src/App.vue
- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/components/ContentCard.vue
- src/vue/backend/src/styles/formContentStyles.scss
- src/vue/backend/src/styles/globalVariables.scss
- src/vue/backend/src/styles/verticalNavBar.scss
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/GuidedSetupContentCard.vue
- src/vue/backend/src/templates/impressListingsAdvancedContent.vue
- src/vue/backend/src/templates/impressListingsGeneralContent.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/layout/Layout.vue
- src/vue/backend/src/templates/layout/Tabbed.vue
- src/vue/backend/src/templates/layout/TwoColumn.vue
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/templates/page.vue
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/children/advancedContentTab.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/SocialPro.vue
- src/vue/backend/src/views/settings/Agents.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/Omnibar.vue
- src/vue/backend/src/views/settings/SocialPro.vue
http://jira.hq.idx.org/browse/UXG-1324
> UXG-1324 match design

- src/vue/backend/src/store/modules/omnibar/index.js
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/views/guided-setup/Omnibar.vue
http://jira.hq.idx.org/browse/UXG-1332
> UXG-1332 updates omnibar defaultPropertyTypeOptions with static list

- src/vue/backend/src/templates/GuidedSetupContentCard.vue
http://jira.hq.idx.org/browse/UXG-1310
> UXG-1310 changes route on dialog dismiss

- src/vue/backend/src/mixins/pageGuard.js
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/AgentsConfigure.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/General.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/ListingsAdvanced.vue
- src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
- src/vue/backend/src/views/settings/General.vue
UXG-1315: Added in the guided setup listings advanced portion, and updated the form changes check so that there aren't unnecessary api calls when the form hasn't been updated.
> UXG-1315: listings advanced update

- add-ons/listings/includes/class-listing-import.php
- idx/admin/apis/import-listings.php
- Added inProgress value to GET return to indicate if the import process is still in progress
- Removed a check for the IDX API class in the listing importer
- Change a delete_option() call to an update_option() call
> Import Listing API GET Changes

- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/guided-setup/ListingsIdx.vue
UXG-1314: Added in the connection of the listings idx tab settings.
> UXG-1314: Connecting idx listings settings

- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/views/children/idxContentTab.vue
> UXG-1330: Corrected lint errors

- src/vue/backend/src/components/listingsCard.vue
- src/vue/backend/src/data/navlinks.js
- src/vue/backend/src/data/productTerms.js
- src/vue/backend/src/mixins/importPages.js
- src/vue/backend/src/repositories/generic.class.js
- src/vue/backend/src/repositories/importContent.class.js
- src/vue/backend/src/router/index.js
- src/vue/backend/src/router/routeMeta.js
- src/vue/backend/src/serviceContainer.js
- src/vue/backend/src/templates/importPageTemplate.vue
- src/vue/backend/src/views/children/importedListings.vue
- src/vue/backend/src/views/children/unimportedListings.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/import/Listings.vue
UXG-1320 Connected the listings importer to the backend, and various routing fixes
- shows social pro and GMB regardless of activation, because activation checks on route were always false
> UXG-1320: connect listings import

- idx/admin/apis/omnibar-settings.php
- idx/admin/apis/settings-general.php
> IMPB-1315: Adds data collection opt-in endpoint field

- idx/admin/apis/enable-addons.php
Refactored the class to be much more dry.
This PR assumes the route will be `/idxbroker/v1/admin/settings/social-pro/enable` instead of `/idxbroker/v1/admin/settings/social-pro/activate`. Can change back if needed.
> IMPB-1291: Cleaned up enable_addons class and added social pro enable/disable

- add-ons/agents/includes/class-taxonomies.php
- add-ons/agents/includes/views/create-tax.php
- add-ons/agents/includes/views/edit-tax.php
- add-ons/listings/includes/class-taxonomies.php
- add-ons/listings/includes/views/create-tax.php
- add-ons/listings/includes/views/edit-tax.php
- Added checks to taxonomy ID input field to prevent invalid inputs for both Agent and Listings classes
- Fixed edit link on taxonomy titles
- Added nonce verification checks
- Added user capability checks
- Cleaned up files which includes:
-- Adding missing brackets on if statements
-- Removed instances of 'var' used to declare class variables
-- Removed any usage of array()
-- Replaced any tabs used for mid-line alignment
> Taxonomy Class Cleanup

- src/vue/backend/src/data/navlinks.js
http://jira.hq.idx.org/browse/UI-1309
> UI-1309 removes faq and gmb

- src/vue/backend/src/store/modules/general/index.js
- src/vue/backend/src/templates/GeneralSettings.vue
http://jira.hq.idx.org/browse/UI-1335
> UI-1335 changes label to opt out

- src/vue/backend/src/mixins/guidedSetup.js
- src/vue/backend/src/mixins/pageGuard.js
- src/vue/backend/src/mixins/standaloneSettingsActions.js
- src/vue/backend/src/store/modules/guidedSetup/actions.js
- src/vue/backend/src/store/modules/guidedSetup/index.js
- src/vue/backend/src/views/children/advancedContentTab.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/settings/Agents.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/Listings.vue
- src/vue/backend/src/views/settings/Omnibar.vue
- src/vue/backend/src/views/settings/SocialPro.vue
UXG-1337: Updated the standalone pages to use a mixin for the repeated methods
> UXG-1337: Updated standalone pages

- idx/widgets/omnibar/create-omnibar.php
- Added missing aria-label to the Omnibar widget
Closes #282
> Added aria-label to omnibar search button

- idx-broker-platinum.php
- Added checks for new feature flags on plugin activation
> Activation Checks

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/mixins/standaloneSettingsActions.js
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/views/settings/General.vue
UI-1348: added refresh plugin options button
> UI-1348: Refresh plugin button

- src/vue/backend/src/components/BulkAction.vue
- src/vue/backend/src/mixins/importActions.js
- src/vue/backend/src/templates/importPageTemplate.vue
- src/vue/backend/src/views/children/importedAgents.vue
- src/vue/backend/src/views/children/importedListings.vue
- src/vue/backend/src/views/children/unimportedAgents.vue
- src/vue/backend/src/views/children/unimportedListings.vue
- src/vue/backend/src/views/import/Agents.vue
- src/vue/backend/src/views/import/Listings.vue
http://jira.hq.idx.org/browse/UI-1334
> UXG-1334 adds import unimport loading

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/components/listingsCard.vue
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/impressListingsAdvancedContent.vue
- src/vue/backend/src/templates/impressListingsGeneralContent.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
- src/vue/backend/src/templates/layout/Layout.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/views/404.vue
- src/vue/backend/src/views/guided-setup/Api.vue
http://jira.hq.idx.org/browse/UI-1344
> UI-1344 fixes for better lighthouse scores

- src/vue/backend/src/components/importFeedback.vue
- src/vue/backend/src/mixins/standaloneSettingsActions.js
- src/vue/backend/src/store/modules/socialPro/index.js
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/SocialPro.vue
UI-1317: Added in intermediate social pro connections. Once the backend is built, these pieces should connect seamlessly. There is a wait on copy for when the user is not subscribed to social pro in middleware. That will be done once the design/copy is ready.
> UI-1317: social pro connection

- idx/admin/apis/settings-general.php
- Added dev partner API key to general settings GET/POST calls
> Dev partner key added to general settings API

- src/vue/backend/src/App.vue
- src/vue/backend/src/components/BulkAction.vue
- src/vue/backend/src/mixins/guidedSetup.js
- src/vue/backend/src/mixins/importActions.js
- src/vue/backend/src/router/index.js
- src/vue/backend/src/store/modules/importContent/index.js
- src/vue/backend/src/templates/importPageTemplate.vue
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/views/guided-setup/Confirmation.vue
- src/vue/backend/src/views/import/Agents.vue
- src/vue/backend/src/views/import/Listings.vue
UI-1349: Bug squash from the plugin
> UI-1349: bug squash

- src/vue/backend/src/components/APIKey.vue
- src/vue/backend/src/store/modules/general/index.js
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/settings/General.vue
UI-1350: added dev code input only when the flag idxdev is set in the url
> UI-1350: dev code input

- src/vue/backend/src/store/modules/listingsGeneral/index.js
- src/vue/backend/src/templates/impressListingsGeneralContent.vue
UI: added in missing Currency code toggle for whether they want to display the currency code on their listings
> UI-1352: Currency code toggle

- src/vue/backend/src/templates/navbar.vue
UI-1329: Added in a fix for a bug where tabbed pages did not highlight the navigation page in the sidebar
> UXG-1329: Fixed navigation bug with tabbed items

- src/vue/backend/src/components/socialProUpgrade.vue
- src/vue/backend/src/views/guided-setup/SocialPro.vue
- src/vue/backend/src/views/settings/SocialPro.vue
UI-1352: added in the social pro draft so we can update it easier once marketing is done with copy
> UI-1352: added draft

- idx/admin/apis/enable-addons.php
- idx/admin/apis/social-pro-settings.php
- idx/admin/rest-controller.php
- idx/idx-api.php
- idx/initiate-plugin.php
- idx/social-pro.php
To test endpoints before they reach staging:
- Add `api.scrum.lan` to your hosts file.
- Checkout app branch with latest endpoints.
- Use api key to account with Social Pro integration.
- Put in scrum url in for `IDX_API_URL` in `initiate-plugin.php`.
- Install [WP Control](https://wordpress.org/plugins/wp-crontrol/) to fire crons immediately.
> IMPB-1292: Adds Social Pro integration

- assets/css/idx-block-edit.min.css
- src/blocks/package-lock.json
- src/css/idx-block-edit.css
- Small change to block editor CSS file to resolve issue of placeholder images not taking up the entire block area
> Block Editor CSS Tweak

- add-ons/listings/includes/class-listings.php
- add-ons/listings/includes/views/wp-listings-adv-fields-settings.php
- Advanced field settings moved to it's own tab under the listings section of the WP dashboard
- Cleanup up class-listings.php
> Moved Advanced Field Settings

- .gitignore
- idx-broker-platinum.php
- idx/initiate-plugin.php
- src/vue/backend/vue.config.js
Before merging this branch, kill the dev server process. For future dev development, set `VUE_DEV_MODE` to `true` in `idx-broker-platinum.php`
> IMPB-1327: Added build process and toggle for dev env

- src/vue/backend/.postcssrc.js
- src/vue/backend/src/App.vue
- src/vue/backend/src/data/productTerms.js
- src/vue/backend/src/router/index.js
- src/vue/backend/src/styles/verticalNavBar.scss
- src/vue/backend/src/templates/layout/Tabbed.vue
- src/vue/backend/src/views/guided-setup/SocialPro.vue
> UI-1349: bug fixes

- src/vue/backend/src/router/index.js
- src/vue/backend/src/views/children/redirectPage.vue
UI: The root level of our page returned a 404. Now I check for a valid api key and send them to general settings if they are valid and the guided set up if they are not
> UI-1349: added in redirect page for top level

- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/views/guided-setup/Welcome.vue
http://jira.hq.idx.org/browse/UI-1365
> UI-1365 bug fixes

- add-ons/listings/includes/class-listing-import.php
- Added check for adv field data during the import process to prevent a log error (supplemental listings do not use that field)
> Added Check for Adv Fields in IDXB Data

- src/vue/backend/src/components/RelatedLinks.vue
- src/vue/backend/src/components/socialProUpgrade.vue
- src/vue/backend/src/mixins/omnibarMixin.js
- src/vue/backend/src/templates/AgentsSettings.vue
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/omnibarForm.vue
- src/vue/backend/src/templates/socialProForm.vue
- src/vue/backend/src/views/children/advancedContentTab.vue
- src/vue/backend/src/views/children/generalContentTab.vue
- src/vue/backend/src/views/children/idxContentTab.vue
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/AgentsConfigure.vue
- src/vue/backend/src/views/guided-setup/Api.vue
- src/vue/backend/src/views/guided-setup/General.vue
- src/vue/backend/src/views/guided-setup/Listings.vue
- src/vue/backend/src/views/guided-setup/ListingsAdvanced.vue
- src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
- src/vue/backend/src/views/guided-setup/ListingsIdx.vue
- src/vue/backend/src/views/guided-setup/Omnibar.vue
- src/vue/backend/src/views/guided-setup/SocialPro.vue
- src/vue/backend/src/views/guided-setup/SocialProConfigure.vue
- src/vue/backend/src/views/settings/Agents.vue
- src/vue/backend/src/views/settings/General.vue
- src/vue/backend/src/views/settings/Listings.vue
- src/vue/backend/src/views/settings/Omnibar.vue
- src/vue/backend/src/views/settings/SocialPro.vue
Bug fixes from http://confluence.hq.idx.org/display/~sarahg/Dev+Coordination+IMPress+Bugs and added links for http://jira.hq.idx.org/browse/UI-1346
> UI-1364: Bug fixes

- idx/views/admin.php
- Added CSS to hide everything but the Vue app on the General Settings tab to prevent notification banners from appearing during page load
> CSS to hide any notification banners

- add-ons/agents/includes/class-agent-import.php
- add-ons/listings/includes/class-listing-import.php
- add-ons/listings/includes/class-listings.php
- add-ons/listings/includes/integrations/wpl-google-my-business.php
- add-ons/utilities/background-processing/impress-listings-background-process.php
- idx/admin/apis/import-agents.php
- idx/admin/apis/import-listings.php
- Fix for incorrect option being used when querying for custom posts
> Option Fix

- src/vue/backend/src/App.vue
- src/vue/backend/src/components/ContentCard.vue
- src/vue/backend/src/mixins/pageGuard.js
- src/vue/backend/src/templates/GeneralSettings.vue
- src/vue/backend/src/templates/GuidedSetupContentCard.vue
- src/vue/backend/src/templates/impressListingsIdxContent.vue
Form changes were getting overwritten, this ups its priority
Bug fixes number 21, 22, 24, 25
> UI-1364: bug fix number 24

- src/vue/backend/src/store/modules/guidedSetup/index.js
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/AgentsConfigure.vue
- src/vue/backend/src/views/guided-setup/Welcome.vue
Added in guided setup social pro beta checks... its not super pretty but i can clean up phase 2
> UI-1364: added in guided setup socialpro skip

- add-ons/listings/includes/class-listing-template.php
- idx-broker-platinum.php
- idx/idx-api.php
- idx/initiate-plugin.php
- idx/leads/class-contact-form-7.php
- idx/leads/class-gravity-forms.php
- idx/leads/class-ninja-forms.php
- idx/register-blocks.php
- idx/shortcodes/register-shortcode-for-ui.php
- idx/views/lead-management.php
- idx/views/multisite.php
- idx/views/search-management.php
- idx/widgets/impress-carousel-widget.php
- idx/widgets/impress-city-links-widget.php
- idx/widgets/impress-lead-signup-widget.php
- idx/widgets/impress-showcase-widget.php
- idx/widgets/omnibar/get-locations.php
- Changed IDXB API version and URL to global constants
- Cleaned up old invocations that previously got the constants from the initiate-plugin.php file
> IDXB API version and url changed to global constants

- idx/views/admin.php
- Hardened CSS meant to hide banners
> Small CSS Change to Catch Additional Banners

- idx/admin/rest-controller.php
- idx/idx-api.php
- idx/register-blocks.php
- idx/social-pro.php
- Fixes IDX API Generic error throwing a notice for the REST API
- IDX API class uses the status code 'Generic' for unknown errors, need to convert that to an actual HTTP status code for the REST API.
- Fixes block editor error with invalid API key
- Fixes Social Pro class failing to create post
> Various bugfixes

- add-ons/listings/includes/class-featured-listings-widget.php
- add-ons/listings/includes/helpers.php
- add-ons/listings/includes/listing-templates/single-listing-classical.php
- add-ons/listings/includes/listing-templates/single-listing-elegant.php
- add-ons/listings/includes/listing-templates/single-listing-luxurious.php
- add-ons/listings/includes/listing-templates/single-listing-solid.php
- add-ons/listings/includes/listing-templates/single-listing-spacious.php
- add-ons/listings/includes/views/single-listing.php
- idx/admin/apis/listings-settings.php
- idx/idx-api.php
- idx/views/lead-management.php
- idx/widgets/create-impress-widgets.php
- Fix for currency code and symbol display on listing templates and the featured listings widget
- Added some additional checks to helpers.php, lead-management.php, and idx-api.php
- Fixed spacing issue in listing-settings.php
- Fixed incorrect function call in create-impress-widgets.php
> Various Fixes

- README.md
- readme.txt
- Updated both readme files with new marketing text
- Set PHP and WP minimum versions
> Readme updates

- idx/idx-pages.php
- Added check to make sure passed in value is an array before attempting to loop through it
> Added Array Check to idx-pages.php

- idx/shortcodes/register-impress-shortcodes.php
- idx/widgets/impress-carousel-widget.php
- idx/widgets/impress-showcase-widget.php
- idx/widgets/impress-widget-helper.php
- Added helper function to show rent/lease or sold prices for featured and supplemental listings for both the IMPress Carousel and Showcase widgets
> Added additional handling for display prices

- README.md
- readme.txt
- Added new FAQ readme
- Update PHP version required in FAQ section
> New FAQ entry added to readme files

- idx/initiate-plugin.php
- Updated capability required to view initial settings page to match the capability required to change settings on that page
> Changed capability required to view general settings page

- idx/widgets/omnibar/create-omnibar.php
- Removed extra array wrapping an omnibar search option
> Fix for option wrapped in extra array

- README.md
- idx-broker-platinum.php
- readme.txt
- Readmes updated and version number bumped
> 3.0.1 readme update

- idx/idx-api.php
> Fix for Logic Issue in get_client_supplementals Call

- idx/register-blocks.php
- idx/widgets/impress-widget-helper.php
- Added blank entry/placeholders to block dropdown menus options
- Added additional empty check for an edge case where a listings is missing both a propType and an idxPropType
> Added default options to block dropdown menus

- idx/widgets/impress-lead-login-widget.php
- idx/widgets/impress-lead-signup-widget.php
- Merged in widget setting defaults with $new_instance variable to prevent missing key warnings when using the legacy block widget
- Comment cleanup
> Lead signup and login widget update

- idx/register-blocks.php
Block registration changes for WordPress 5.8
> Changes to block registration file

- idx/idx-api.php
Simplified price comparison function by using PHP 7's spaceship operator
> Updated price comparison function

- add-ons/listings/includes/class-listing-import.php
- Added empty check for the settings key 'wp_listings_idx_update' before using it during the listing update process
> Added check for empty key

- add-ons/listings/includes/class-listing-import.php
- idx/widgets/create-impress-widgets.php
Couple of minor changes missed by other tickets: 
- Added check for key value before accessing
- Changed back to a loose comparison for the $use_rows value
> Some minor fixups

- add-ons/listings/includes/class-listings-search-widget.php
- Added shortcode option to existing legacy widget
- Added scope to function declarations
> Added shortcode option for legacy listings search button widget

- add-ons/agents/includes/class-employee-widget.php
- Added shortcode option to existing legacy widget
- Added scope to function declarations
> Added shortcode for legacy agent widget

- idx/shortcodes/register-idx-shortcodes.php
- idx/shortcodes/shortcode-ui.php
- idx/widgets/create-idx-widgets.php
- idx/widgets/idx-middleware-widget.php
- idx/widgets/idx-widget-class.php
Removed MapQuest script from map widget in preparation for move to Azure.
> Script change for map search widget

- README.md
- idx/register-blocks.php
- readme.txt
Final readme and 'version tested to' updates added
> Final 3.0.4 changes

- add-ons/agents/includes/class-agent-import.php
- add-ons/agents/includes/views/single-employee.php
- idx/idx-api.php
- idx/register-blocks.php
- idx/shortcodes/register-idx-shortcodes.php
- idx/widgets/impress-city-links-widget.php
Added checks for WP_Errors before attempting to use returned IDXB API data in various files throughout the plugin
> Added some additional checks when interacting with the IDXB API

- add-ons/agents/includes/class-agent-import.php
- add-ons/agents/includes/class-employee-widget.php
- add-ons/listings/includes/listing-templates/single-listing-classical.php
- add-ons/listings/includes/listing-templates/single-listing-elegant.php
- add-ons/listings/includes/listing-templates/single-listing-luxurious.php
- add-ons/listings/includes/listing-templates/single-listing-solid.php
- add-ons/listings/includes/listing-templates/single-listing-spacious.php
- add-ons/listings/includes/views/listing-details-metabox.php
- add-ons/listings/includes/views/single-listing.php
- add-ons/listings/includes/wp-api.php
- add-ons/listings/plugin.php
- assets/webfonts/neuton-raleway-font.css
- idx/idx-pages.php
- idx/initiate-plugin.php
- idx/leads/class-contact-form-7.php
- idx/notice/notice-handler.php
- idx/shortcodes/register-impress-shortcodes.php
- idx/views/lead-management.php
- idx/views/search-management.php
- idx/widgets/create-impress-widgets.php
- idx/widgets/idx-widget-class.php
- idx/widgets/impress-carousel-widget.php
- idx/widgets/impress-city-links-widget.php
- idx/widgets/impress-lead-login-widget.php
- idx/widgets/impress-showcase-widget.php
- idx/wrappers.php
2nd round of changes to sanitize/escape everything possible
> Round 2 for security audit changes

- add-ons/listings/includes/class-listing-import.php
- add-ons/listings/includes/views/wp-listings-adv-fields-settings.php
- Added back missing function required to import advanced field names
- Added check for array before using count() to prevent log warnings
> Fix-up for Advanced Field name importer

- README.md
- idx-broker-platinum.php
- readme.txt
Already includes #410  and #412 - Both which haven't been sent to WP
> version bump

- idx/admin/apis/omnibar-settings.php
Merging omnibar blacklist code changes to the latest 3.0.9 branch
> Blacklist 4 core fields from custom field options

- idx/views/lead-management.php
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
What process did you follow to verify that your change has the desired …
> IMPB-1443: remove sanitization from API POST

- idx/idx-pages.php
🐛 Are you fixing a bug? Y
💻 Are you changing functionality? Y
Depending on the hosting environment and update schedule, a WordPress site using IMPress will eventually become inaccessible if the account it retrieves data from has thousands of pages and links that have to be created or updated within the create_pages_from_chunk function in idx-pages.php.
Looking over the code within the plugin, I have identified a few areas that are the cause of some slowdown:
find_and_update_post makes a call to get_posts() to get a list of posts to look through and see what needs to be updated to match what is from the account. find_and_update_post is called separately for every single link, which means if you have 1000 saved links 1000 queries will be made against the database. 
update_post determines …
> IMPB-1504   IDX Pages generation can make a WordPress site unresponsive when an account has thousands of links

- idx/views/search-management.php
- src/js/idx-searches.js
Reverts idxbroker/wordpress-plugin#478
> Revert "IMPB-1502 - Fix for wrong bathroom term in saved links"

- README.md
- add-ons/listings/includes/listing-templates/listing-map-location.php
- add-ons/listings/includes/listing-templates/single-listing-classical.php
- add-ons/listings/includes/listing-templates/single-listing-elegant.php
- add-ons/listings/includes/listing-templates/single-listing-luxurious.php
- add-ons/listings/includes/listing-templates/single-listing-solid.php
- add-ons/listings/includes/listing-templates/single-listing-spacious.php
- assets/js/idx-leads.js
- idx/views/lead-management.php
- idx/widgets/impress-carousel-widget.php
- idx/widgets/impress-showcase-widget.php
- readme.txt
- src/vue/backend/src/templates/navbar.vue
- src/vue/backend/src/views/guided-setup/Agents.vue
- src/vue/backend/src/views/guided-setup/AgentsConfigure.vue
- src/vue/backend/src/views/guided-setup/Welcome.vue
The issue was related to the lead email being broken on submission, in addition to that there's a QOL change to how the page reacts after the lead is successfully submitted.
> IMPB-1499: Fixed the email symbol sanitation and submission actions.

- README.md
- readme.txt
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
What process did you follow to verify that your change has the desired …
> IMPB-1539: Removed IXACT references

- idx/initiate-plugin.php
Included Lain's fix for our conflicting script for "Feeds for YouTube Pro Personal" Smash Balloon plugin
> IMPB-1508: Added Lain's fix for vue conflict

- README.md
- add-ons/listings/plugin.php
- idx/initiate-plugin.php
- readme.txt
- src/react/apps/GoogleMyBusinessSettings.js
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
What process did you follow to verify that your change has the desired …
> Changes for Rapid Release/3.2.1

- .gitignore
- README.md
- add-ons/agents/includes/shortcodes.php
- add-ons/listings/includes/shortcodes.php
- idx-broker-platinum.php
- idx/shortcodes/impress-lead-signup-shortcode.php
- idx/shortcodes/register-idx-shortcodes.php
- idx/shortcodes/register-impress-shortcodes.php
- idx/widgets/create-impress-widgets.php
- idx/widgets/omnibar/create-omnibar.php
- readme.txt
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
What process did you follow to verify that your change has the desired …
> IMPB-1551: Sanitized the shortcode inputs
