composer.json

* #79 Removed wpreadme2md from composer.json as it's no longer used.

removed wpreadme2md as it's no longer used.

---

idx/shortcodes/register-impress-shortcodes.php
idx/widgets/impress-carousel-widget.php

Prevents duplicate listings from appearing in carousel widget when number of listings is less than the number of display slots.

Fix for duplicate entries in IMPress Property Carousel widgets

---

idx/shortcodes/register-impress-shortcodes.php
idx/widgets/impress-carousel-widget.php

Fix to prevent IMPress Carousel widget from loading before jQuery on themes where it is placed in wp_footer (e.g. the "Twenty Nineteen" theme).

Prevent IMPress Carousel widget from loading before jQuery

---

idx/initiate-plugin.php

Prevents duplicate cron entries when using the "Refresh Plugin Options" button.

Fix for duplicate omnibar location cron jobs

---

assets/css/idx-shortcode.css

Minor CSS tweak to prevent the IDXB shortcode button from expanding past its bounds when using the classic editor.

WP-1046: CSS Change to Prevent Shortcode Button from Changing Dimensions

---

idx/shortcodes/register-impress-shortcodes.php

This is to avoid error log entries when placing a widget using the Gutenberg editor.

Added handling for missing $instance

---

idx/idx-pages.php

'$this->app->make()' does not work as '$this' does not have a property called 'app' when 'make()' is called. Changed the line to simply return a new instance of the 'Add_Uid_To_Idx_Pages' as that appears to be the end-goal here.

Changes to how 'Add_Uid_To_Idx_Pages' is returned when the 'idx_added_uid_to_idx_pages' option is empty

---

idx/widgets/omnibar/create-omnibar.php

Added permission_callback attribute to omnibar rest route registration to prevent error log notices in WordPress 5.5

Added public callback permission

---

idx/register-blocks.php

Updated block registration types to prevent error log notices in WordPress 5.5:
int -> integer
bool -> boolean

Updated register-blocks.php attribute types

---

idx/idx-api.php

Changed from exact string matching to case-insensitive sub-string matching to determine Pt/Home account levels.

Simplified Pt-level account check

---

idx/widgets/omnibar/create-omnibar.php

* Updated default property type value to 'all' so it matches the default value shown in the omnibar settings UI, 'All Property Types'

Updated default omnibar prop type to match UI

---

idx/idx-pages.php

- Replaced wp_get_scheduled_event() function calls to avoid raising required WP version at this time.

Replaced wp_get_scheduled_event() function calls in idx-pages.php

---

idx/shortcodes/register-impress-shortcodes.php
idx/widgets/impress-carousel-widget.php

Removed duplicate settings options in the OwlCarousel instance used to power the IMPress Carousel widget

Removed duplicate OwlCarousel options

---

idx/initiate-plugin.php
idx/widgets/omnibar/create-omnibar.php

* Added an extra check when enqueuing the locationlist script to handle cases where a customer has SSL enabled on their site but do not have 'https' correctly set in the WP Dashboard
* Added a direct call to create the locationlist file to the Refresh API Options button on the plugin settings page so the Omnibar widget is ready to use immediately after activating the plugin vs waiting for the scheduled cron task to fire off later in the day

Omnibar SSL Misconfiguration Handling

---

idx/shortcodes/register-impress-shortcodes.php
idx/widgets/impress-showcase-widget.php

Updated agent ID check for showcase widgets as a missing/empty userAgentID on a property could cause a false match.

Fix for agent matching issue

---

assets/css/idx-broker.css
src/vue/backend/src/App.vue
src/vue/backend/src/components/BulkAction.vue
src/vue/backend/src/data/navlinks.js
src/vue/backend/src/mixins/Tabbed.js
src/vue/backend/src/router/index.js
src/vue/backend/src/router/routeMeta.js
src/vue/backend/src/templates/impressListingsAdvancedContent.vue
src/vue/backend/src/templates/layout/Generic.vue
src/vue/backend/src/templates/layout/Layout.vue
src/vue/backend/src/templates/layout/Tabbed.vue
src/vue/backend/src/templates/layout/TwoColumn.vue
src/vue/backend/src/views/import/Agents.vue
src/vue/backend/src/views/import/Listings.vue
src/vue/backend/src/views/settings/Agents.vue
src/vue/backend/src/views/settings/GMB.vue
src/vue/backend/src/views/settings/General.vue
src/vue/backend/src/views/settings/Listings.vue
src/vue/backend/src/views/settings/Omnibar.vue
src/vue/backend/src/views/settings/SocialPro.vue

* Adds "routerMeta" export for tabbed child nav pages / passes props to parent component
* Adds various layout scaffolding templates and views
* Modified Sarah's "importHeader.vue" into "Tabbed.vue" for reusability between tabbed views.
* Removed padding from `#wpcontent` element as it throws off our page padding
* Various other tweaks.

UXG-1298: Added nested router views and layout scaffolding.

---

src/vue/backend/src/mixins/pageGuard.js
src/vue/backend/src/serviceContainer.js
src/vue/backend/src/templates/AgentsSettings.vue
src/vue/backend/src/views/settings/Agents.vue

Also:
* Made `pageGuard.js` change so dispatching `setItem` does not rely on the local action being imported into the parent component - instead, reference the module.
* Reverted to the Destructured args in `serviceContainer` so that multiple args passed (for post method) are copied over.

UXG-1245: GET/POST agent settings from/to WP REST API backend.

---

idx/shortcodes/register-shortcode-for-ui.php

- Resolves notice thrown in WP 5.7 about not passing an array value to wp_localize_script

Wrapped Value in Array to Stop Log Notices

---

add-ons/listings/includes/views/wp-listings-gmb-settings.php
add-ons/listings/plugin.php

- Removed old constants from IMPress Listings that have been replaced by the constants created in the core plugin
- Removed remaining reference to wp_resource_url/WP_LISTINGS_URL that are no longer required

Removed Old IMPress Listing Constants

---

idx/notice/notice-handler.php
idx/register-blocks.php
idx/shortcodes/impress-lead-signup-shortcode.php
idx/views/omnibar-settings.php
idx/widgets/impress-lead-signup-widget.php
idx/widgets/omnibar/create-omnibar.php

- Updated the remaining wp_localize_script calls that weren't covered in the initial round of fixes. All non-array values supplied to wp_localize_script are now wrapped in an array.

Updated any remaining localize script calls 

---

idx/dashboard-widget.php
idx/initiate-plugin.php

- Added Guided Setup links to plugin page and admin bar
- Updated dashboard widget to point to the guided setup page instead of general settings when no API key is set
- Admin bar top level link will change to guided setup page if no API key is set

Plugin page and admin bar link changes

---

add-ons/listings/includes/listing-templates/listing-inquiry-form.php
add-ons/listings/includes/listing-templates/single-listing-classical.php
add-ons/listings/includes/listing-templates/single-listing-elegant.php
add-ons/listings/includes/listing-templates/single-listing-luxurious.php
add-ons/listings/includes/listing-templates/single-listing-solid.php
add-ons/listings/includes/listing-templates/single-listing-spacious.php

- Updated some options checks in custom listing templates as they were just checking for empty string instead of using empty()
- Explicitly adds the impress signup shortcode in the listing inquiry signup form to cover Lite accounts

Updated Listing Template Option Checks

---

idx/views/lead-management.php

- Skipped displaying large HTML table previews of emails leads receive in the lead management section of the plugin

Issue with Large Email Preview Lead Notes

---

idx/admin/apis/listings-idx-settings.php

- Fix for incorrect key name which prevented the custom imported listing title setting to not save correctly

Fix for import title not saving

---

idx-broker-platinum.php
idx/admin/apis/enable-addons.php

(This flow is the exact same for IMPress Agents)
- User has IMPress Listings installed and install IMPress for IDX 3.0.0
- The existing IMPress Listings install works as is.
- If the user checks 'Enable Listings' in the new IMPress for IDX dashboard
- IMPress Listings is deactivated
- Our consolidated version of Listings is used
- User does not have IMPress Listings installed and installs IMPress for IDX 3.0.0
- 'Enable Listings' is unchecked
- User can install and use the legacy IMPress Listings
- 'Enable Listings' is checked
- User cannot activate IMPress Listings (currently throws an error on activation, but will throw a human readable message pending IMPress Listings update)

IMPB-1296: Adds legacy plugin checks and deactivation logic

---

src/vue/backend/src/App.vue
src/vue/backend/src/store/modules/alerts/index.js
src/vue/backend/src/templates/layout/Layout.vue
src/vue/backend/src/templates/navbar.vue
src/vue/backend/src/views/children/redirectPage.vue
src/vue/backend/src/views/settings/General.vue

Fixed bug where the page is always redirecting to guided setup on / even when its supposed to go to the general settings page when the api key exists regardless of validity. Added in content skeleton screens to match

UI-1364: bug fixes

---

idx/views/lead-management.php

- Corrects URL used for the add saved search button when editing a lead

Fix for add saved search button not working

---

idx/idx-pages.php
uninstall.php

- Resolves issue where idx_page posts are duplicated when in a non-published status
- Added ability to delete or re-publish any idx_page posts moved to draft or pending review status
- Uninstalling the plugin now correctly deletes all idx_page posts, regardless of status

Fix for pending idx_page duplication issue

---

idx/widgets/impress-lead-login-widget.php

- Added missing 'password_field' default option to prevent invalid key errors

Added missing default option to IMPress Lead Login widget

---

idx/initiate-plugin.php

- Dequeues/deregisters scripts from the 'uListings' and 'Graphs & Charts' plugins from the IDXB General Settings page to prevent conflicts

Dequeue scripts from conflicting plugins

---

idx/widgets/impress-widget-helper.php

- Added formatting to rent/lease price as well as sold price (while listingPrice data is formatted in the IDXB API the other prices are not)
- Changed default currency symbol from '' to '$' in the widget helper price selection function (Users that want a different symbol to be shown can do so using the currency symbol option found in the listings add-on settings)

Changed default symbol and added formatting for sold/rent price

---

idx/admin/apis/enable-addons.php

- Added flush_rewrite_rules call after activating listings or agents so users do not need to visit the permalinks page

Fix for Missing '/listings' page

---

add-ons/listings/includes/class-listing-import.php
idx/admin/apis/listings-idx-settings.php

Resolves issue with the auto import listings cron job still being scheduled after disabling the setting

Unscheduling Auto Import Listing Cron Job

---

idx/widgets/impress-showcase-widget.php

- Applied widget settings defaults to $new_instance to prevent debug log warnings when used with the legacy block widget
- Added 'acres' default field
- Replaced some ternary operators with null coalescing operators where possible
- Replaced price compare function logic with spaceship operator
- Cleaned up comments

IMPress Showcase widget changes

---

idx/widgets/impress-carousel-widget.php

- Applied widget settings defaults to $new_instance to prevent debug log warnings when used with the legacy block widget
- Added 'acres' default field
- Replaced some ternary operators with null coalescing operators where possible 
- Replaced price compare function logic with spaceship operator
- Cleaned up comments

IMPress Carousel Cleanup

---

idx/widgets/omnibar/idx-omnibar-widget.php

Applies widget defaults to $new_instance to prevent missing key warnings from being thrown when using the legacy block widget

Update Omnibar for legacy block widget

---

idx/widgets/impress-city-links-widget.php

- Merged $new_instance with widget defaults to prevent missing key warnings when using the legacy block widget
- Comment cleanup
- Replaced ternary operator with null coalescing operator

Changes to IMPress City Links widget

---

assets/css/idx-block-edit.min.css
src/css/idx-block-edit.css

Small margin change to prevent gap from appearing when a block container is selected/active.

CSS change to fix small gap at bottom of block container

---

idx-broker-platinum.php

- Hides legacy widgets from the new legacy block ( there are already block implementations for those widgets )
- Updated the PHP version check to use the proper version_compare function

Hide widgets from legacy block

---

idx/shortcodes/register-impress-shortcodes.php

- Changed check on $use_rows back to a loose comparison to resolve issue with widgets created using saved links.

Changed $use_row Check

---

idx/idx-api.php
idx/register-blocks.php
idx/shortcodes/register-shortcode-for-ui.php
idx/widgets/impress-carousel-widget.php
idx/widgets/impress-lead-signup-widget.php
idx/widgets/impress-showcase-widget.php

- Changed check on the get_agents_select_list() function found in idx_api.php to prevent missing key warnings when access ing 'agent'
- Removed duplicate versions of get_agents_select_list() functions from various widget files. Those files already have an instance of idx_api so they have access to the function from there
- Updated key check in agent select list function in the block registration file (this version was not consolidated as it returns just the agent data to be used with the block editor instead of <option> elements used by the legacy widgets)

Consolidated get agent select list functions

---

idx/idx-api.php
idx/widgets/impress-widget-helper.php

Added method to IDX API class to get listings count from a saved link ID. Currently the API limits returned saved link results to 250 listings so savedlinks/{link_id}/count must be used instead to get the real number of results.

Added Convenience Method to IDX API Class for Saved Link Listing Count

---

idx/widgets/impress-widget-helper.php

Added 'idxStatus' as fallback for 'status' field to avoid log errors as some sold supplemental listings have one field set but not the other.

Status field fallback for price_selector helper function 

---

idx/leads/class-contact-form-7.php

Please exaplin the intent of your Pull Request.
Fixed not saving email and email2 options in Contact Form 7.
The is_email function was used to validate the data and it is invalid in this context. The values for the email and email2 options are never the actual email address, although their name may suggest.
Manually checking if saving options works correctly after changing.

fix cf7 options sanitize

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
add-ons/agents/includes/class-employee-widget.php
add-ons/listings/includes/class-featured-listings-widget.php

1.  Fixed a bug where the widget was being returned encoded HTML rather than raw HTML resulting in <div class="...... displaying on the site, rather than the widget. #409 
2.  Fixed a typo in this pull request template
What process did you follow to verify that your change has the desired effects?
- How did you verify that all new functionality works as expected?
-- Edited widget in WP editor. Added a console.log script in various places of a listing and added esc_html earlier in the widget function where data is being added rather than at the end when the widget is being outputted.
- How did you verify that all changed functionality works as expected?
-- Widget functioned as expected and malicious scripts that I added (the console.logs) were displayed instead of run
- How did you verify …

IMPB-1429 - Fix encoded html text from displaying

---

idx/shortcodes/register-impress-shortcodes.php

IMPress Lead Signup widget - password field label improperly encoded as string

IMPB-1439: Lead Signup widget pwd label decoded

---

README.md
idx/leads/class-gravity-forms.php

- Fixed typo calling sanitize function
- Fixed IDX Broker Logo not displaying on settings pages
- Update tooltips to match other GravForms 2.5 UI tooltips / more accessible
- Added refresh on save to ensure user submitted settings are displaying properly

IMPB-1442: Gravity form 2.5 tooltip update - typo in sanitize function

---

idx/widgets/impress-lead-signup-widget.php

Only 1 instance of `sanatize_text_field` in the whole repository, which is causing an fatal error in some cases
There are 105 instances of `sanitize_text_field`. 
```
Fatal error: Uncaught Error: Call to undefined function IDX\Widgets\sanatize_text_field()
in /www/wp-content/plugins/idx-broker-platinum/idx/widgets/impress-lead-signup-widget.php on line 17
Call stack:
IDX\W\Impress_Lead_Signup_Widget::__construct()
wp-includes/class-wp-widget-factory.php:61
WP_Widget_Factory::register()
wp-includes/widgets.php:115
register_widget()
wp-content/plugins/idx-broker-platinum/idx/widgets/create-impress-widgets.php:43
IDX\W\Create_Impress_Widgets::register_impress_widgets()
wp-includes/class-wp-hook.php:303
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:327
WP_Hook::do_action() …
```

Typo in function name cause fatal error

---

src/vue/backend/src/templates/omnibarForm.vue

add check for MLSName existence to the addCleanLabel() function in omnibarForm.vue to prevent the settings page from breaking.
Some users have observed that the Omnibar settings page within the IMPress plugin breaks under certain circumstances---it seems to be related to custom fields that are set for an at the time active MLS feed on the IDX Broker account. When the MLS feed becomes deactivated or removed from the account, the call to wp-json/idbroker/v1/admin/settings/omnibar (used on the Omnibar settings page) does not include data for the removed or deactivated MLS which in turn causes findMLSName() in omnibarForm.vue to return null when it tries to look up information for each custom field that was added while the now-removed MLS was still active on the account.
...yeah, it's kind of …

IMPB-1461  Omnibar gives a "Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')" when trying to search

---

idx/idx-api.php
idx/widgets/omnibar/get-locations.php

An uncommon issue that occurs with our clients is that if the Omnibar is set to retrieve a list of cities, counties, or zipcodes for an MLS that is then removed from the IDX Broker account, the next time the locationlist.js file is generated it will contain instances of "Required parameter missing or invalid." the 400 error code message returned by our API. This breaks the Omnibar search functionality on the frontend of the site until the old MLS IDs are removed from the WordPress site configuration or new MLS IDs are set for the cities, counties and zipcode location options for the Omnibar.
This change adds detection for 400 responses from our API and with that detection will retry any errored city, county or zipcode requests with the default 'combinedActiveMLS' list.
- With a test …

Handling city, county and zipcode 400 errors causing the Omnibar to break when an MLS is no longer available on an account

---

idx/wrappers.php

use $meta_value instead of find_idx_url and $idx_page_id when setting the dynamic wrapper for an IDX Broker page from the "edit wrapper" WordPress page
$meta_value is provided by the wrapper page being edited within WordPress and is already set to the internal page ID or saved link ID that needs to be used when sending an update to /dynamicwrapperurl, so using it instead of trying to lookup the ID via the WordPress wrapper post ID resolves the behavior where trying to set a wrapper for a specific IDX Broker page from the Edit Wrapper page was instead always setting the global wrapper
The followings screenshot shows the "Apply Wrapper to IDX Pages" metabox where the user would choose what page they want to apply the wrapper to:
--------
Verified corrected behavior by creating and editing a …

IMPB-1458  Impress wrapper tool does not respect the selected page in the "Apply wrapper to IDX pages" dropdown

---

src/vue/backend/vue.config.js

the backend of the IMPress plugin is built with Vue. these components are packaged with webpack and loaded through the publicPath url when going to the settings page for IMPress. before this PR the publicPath url is set to the following:
`'/wp-content/plugins/idx-broker-platinum/assets/vue/backend'`
when a WordPress site is installed at the root level, there isn't any issue with this. `https://example.com/wp-admin/` will load the backend chunks from `https;//example.com/wp-content/plugins/idx-broker-platinum/assets/vue/backend`.
however, if a WordPress site is installed at a subdirectory like `https://example.com/site1/`, the wp-content files will be located at `https://example.com/site1/wp-content/...`. but the above pathing for publicPath means the chunks are still attempted to be …

IMPB-1448 IMPress plugin chunk loading errors when WP is installed on subfolder domain

---

idx/leads/class-contact-form-7.php

in PHP8 it is a fatal error to call non-static methods in a static way.
this is something that CF7 does with the functions we provide in idx\leads\class-contact-form-7.php and most of the functions are static except for idx_save_lead_settings and idx_put_lead.
i don't see any issues with making these functions static as well and doing so makes our plugin compatible with cf7 in PHP8.
attached is a zip file with the changes applied to IMPress 3.0.9's class-contact-form-7.php file for testing. i've tested this on both PHP8.0 and PHP7.4 with a simple contact form linked through the IDX Broker API and leads are submitted successfully on both versions.
during testing, i had to resave the CF7 form when uploading new versions of the plugin to reconnect the form to the IDX Broker account---you may …

IMPB-1460 CF7 and IDX Broker plugin error on PHP8 on form submission

---

idx/views/search-management.php

1. Main sidebar menu refers to saved links as 'Saved Searches'. [151667b](https://github.com/idxbroker/wordpress-plugin/pull/446/commits/151667bddbd8183343007945692c64f6d1cf54a3) updates the menu item text to 'Saved Links'
2. Links to edit saved links in middleware are improperly formatted. [ef5b915](https://github.com/idxbroker/wordpress-plugin/pull/446/commits/ef5b915991cd2ab1643fad9e73671b11e212f98f) updates the generated link to take the user to the correct page.
1. Verify sidebar menu name for IMPress > Saved Searches with and without the changes in place
2. Navigate to IMPress > Saved Searches, click on edit search in middleware icon with and without changes in place
Fix: IMPress > Saved …

IMPB-1468 Edit Saved Link URL is incorrect

---

idx/views/lead-management.php

idx_lead_add is used when a user tries to create a new lead through Leads > Add Lead within WordPress.
when the 'Add Lead' form is submitted, it's first serialized with $.serialize. this converts the form into a percent encoded form which is sent to the server.
the server receives the percent encoded form and uses sanitize_text_field to sanitize it. however, since emails contain an @ symbol like in test@example.com, the @ symbol in the address was converted into a percent encoded form. looking at the source code for WordPress's sanitize_text_field, it removes percent encoded characters from the string in addition to the rest of the checks it does. this results in the @ symbol being effectively stripped away from …

IMPB-1476  Unable to create leads via IMPress plugin add lead form

---

idx/views/lead-management.php

Lead names are linked within Leads > Leads for leads within IMPress/IDX Broker. The links on the left are missing the nonce, so when the name is clicked on the left instead of being able to edit the lead a nonce error appears.
This fix adds the nonce back to the lead link.
Add nonce to the edit leads name link within Leads > Leads when using WordPress.
Click on the lead's name with and without the change in place when looking at Leads > Leads
N/A
Pull Requests must have the sign-off of two other …

IMPB-1477 Clicking on Lead name within Leads > Leads produces a nonce error

---

idx/views/lead-management.php

When editing a saved property for a lead through IMPress, 'name' is the name of the field used to send the name of the property to the API. This is different from the expected 'property_name' within the plugin code, causing the name to be erased when the saved property is edited.
This change adjusts the name referred to in the plugin backend for this field from 'property_name' to 'name' so that the name for a saved listing can be properly updated.
Edit and save the name for a saved property for a lead within IMPress with and without the changes in place.
Fix: The name for a lead's saved property can again be updated through IMPress.
Pull Requests must have the sign-off of two other developers …

IMPB-1469 Editing saved property removes name value

---

idx/views/lead-management.php

URLs in IMPress to edit a lead's saved property in MW are improperly formatted and direct the user to create a new property instead when clicked.
This PR reformats the generated URL so that the expected listing is brought up for editing when the 'Edit Property in Middleware' icon link is clicked.
Click on a 'Edit Property in Middleware' icon link for a saved listing for a lead with and without the changes in place.
Fix: 'Edit Property in Middleware' icon links for a lead's saved listings now take the user to the correct Middleware page.

IMPB-1470  Edit Leads saved property URL is incorrect

---

idx/views/lead-management.php

Attempting to delete a lead's saved search through the trashcan icon in IMPress does nothing. This is because the field name for the saved link ID is sent as 'ssid' but the backend is expecting 'spid'.
This PR changes spid to ssid in variable name and $_POST variable to match the id submitted by Edit Lead UI.
Attempt to delete a saved search for any lead from within IMPress with and without the changes in place.
Fix: A lead's saved searches can again be deleted through IMPress by clicking on the trash icon.

IMPB-1471 Unable to delete lead saved search from IMPress dashboard UI

---

idx/views/lead-management.php

The code generating traffic history rows for a lead within IMPress was doing so outside of the traffic history table.
This change moves the relevant code block so that the rows are inside the table as expected.
View the traffic history for a lead with traffic history with and without the fix in place.
Fix: Traffic history for a lead is again displayed in a table format

IMPB-1472  Lead Traffic History is not populating inside table

---

idx/leads/class-contact-form-7.php

PHP8 doesn't like it if you try to use a non-existent key on an array (when checking for selected tags) or if you try to access a boolean as an array (get_option can return false)
rewrote code to avoid warnings
Review PHP error log (or enable the display of warnings) when using the IDXB-CF7 tab to create and edit new forms and link them to IDXB.
fix: resolve PHP8 errors when generating UI for IDXB tab in CF7

IMPB-1479  CF7 and IDX Broker PHP warnings in WP Dashboard on PHP 8.0

---

assets/js/idx-leads.js
idx/idx-api.php
idx/views/lead-management.php

Leads are able to successfully be deleted within Leads > Leads when using IMPress but the data does not refresh due to how lead related data is cached inside an option---the plugin tries to clear the idx_leads_lead_cache option, which isn't ever actually set due to the offset being added to the name of cached lead data.
To ensure the list of leads are immediately updated as expected, the following changes were made:
1. Added optional $name parameter to idx_clean_transients so that specific types of cached data can be deleted by themselves
2. Updated lead-management.php lead-deletion-functions to make use of the new idx_clean_transients functionality and added 'lead-row' class to lead rows generated on Leads > …

IMPB-1434 Unable to Delete Leads from IMPress plugin

---

assets/js/idx-leads.js

This PR adds PHP timestamp detection and ordering to DataTables which is used to display leads and lead related data within Leads > Leads. 
Prior to this change, DataTables was not detecting the timestamp provided by the PHP side of IMPress and was thus sorting timestamp columns lexicographically.
With this change in place, timestamp columns are properly detected and sorted by date and time as expected.
Sort the Leads > Leads table by any date columns (like Subscribed or Last Active) with and without the change in place.
Fix: properly sort timestamp columns for lead related tables in Leads > Leads

IMPB-1491: Sort timestamps correctly in DataTables (used in Leads > Leads)

---

idx/widgets/impress-showcase-widget.php

Impress-property-showcase is the classname used by our CSS to style the widget and arrange the listings according to the "listings per row" option---this classname property is also used by page builders like beaver builder when inserting our widgets into the page.
This PR adds impress-property-showcase to classname set for the showcase widget.
Prior to this change the classname set on the showcase widget was impress-showcase-widget, which was not targeted by our CSS and causing the columns to not be formatted as expected when using a page builder to insert the widget.
Impress-showcase-widget has been left in the classname to avoid breaking any CSS created by clients or developer partners that might be using it to style our widget.
Add a Showcase widget to a …

IMPB-1247 IMPress Showcase widget does not apply column settings when using page builder widget

---

idx/idx-pages.php

Some clients have reached out indicating that they are unable to get their IDXB pages to appear within the IDX Pages section of IMPress. Sometimes the pages disappear and sometimes they are never there at all. Even when trying to rerun the idx_create_idx_pages WP cron manually with a tool like WP Crontrol the pages fail to be created or recreated every time. 
The exact circumstances that cause this behavior are still unclear but after thoroughly investigating what happens on an affected developer partner client’s site I’ve determined some details and a possible fix. 
On the affected site when adding debug statements to the plugin’s code I found that when create_idx_pages() was being executed, it was always being …

IMPB-1497 idx pages sometimes never populate through create idx pages

---

src/js/idx-omnibar.js

Square brackets (like `[]`) are added to the idxStatus fields in the search page URLs used by the Omnibar to show Address and Listing ID searches to the user. This ensures that both sold and active listings can be shown in the search.
1. Apply fix and rebuild plugin.
2. With rebuilt plugin active on a site, perform an Omnibar search for both a sold and active listing for both the listing ID search and the address search on a connected MLS.
3. Note that both sold and active listings are included in the search results.
Fix: Omnibar address and listing ID search more consistently shows both sold and active listings in the results.

IMPB-1498  Omnibar only searching for sold listings with IMPB-1465

---

idx/idx-pages.php

Additional commit for PR https://github.com/idxbroker/wordpress-plugin/pull/466
$wpdb needs to be declared as global to be used properly.
With fix in place, confirmed that IDX Pages are pulled in on a new install, and new saved links that are created are pulled in on refresh.
n/a

IMPB-1497-2 idx pages sometimes never populate through create idx pages

---

idx/widgets/create-impress-widgets.php
idx/widgets/impress-showcase-widget.php
src/css/widgets/impress-showcase.css

Fixups for showcase widgets
Shortcode: add css styling so the rows don't end early
Page Builder plugins: add class so the rows don't end early
What process did you follow to verify that your change has the desired effects?
Tested in local build on 3.1.0
Compared Shortcode, Builder Plugin, and WP gutenburg editor designs before and after each changed line of code
All designs match much better than before
Fixed inconsistencies in IMPress showcase across different implementations

Impb 1247 fix rows

---

src/js/idx-omnibar.js

When a client uses the Omnibar to search for a word without spaces, prior to this PR it is sometimes considered a ListingID even when it contains no numbers. For example, if you search "Morris" in an Omnibar under 3.0.10 you are directed to a listingID search for Morris which returns nothing when you may have expected it to do an address search with Morris instead.
Note that the previous check for whether something was a listingID effectively only took into account whether there were spaces
The new check for the Omnibar now only considers a string with the following characteristics to be a listing ID:
1. must have at least 1 digit somewhere
2. no spaces
3. is a combination of alphanumberics, _, and -
A string with all of the above characteristics is assumed to …

IMPB-1495  Omnibar is reading in typed info as the Listing ID

---

idx/initiate-plugin.php

🐛 Are you fixing a bug? Y
Custom cron schedules are registered in initiate-plugin.php, but prior to this PR were registered after all other classes were instantiated. This meant that if a class tried to schedule a WP cron event with a custom schedule, it would actually not be successfully scheduled.
Moving $this->register_cron_schedules(); to the top of instantiate_classes() resolves this issue.
Attempt to change the update frequency of the plugin to a custom schedule like "twice a week" with and without the fix in place. You can use WP Crontrol to determine what events have been successfully scheduled.
Fix: IMPress Cron events are scheduled more reliably 

IMPB-1500  Changing the Update Frequency of IMPress removes Cron events 'create_idx_pages' and 'delete_idx_pages'

---

idx/views/search-management.php
src/js/idx-searches.js

We don't use `ba` in search, we use `tb`
updating saved link creation, and the forms that create them to use `tb`

IMPB-1502 - Fix for wrong bathroom term in saved links

---

add-ons/listings/includes/class-listing-import.php

'update-excluding-images' is the string that the wp_listings_idx_update option is set to when the user chooses the 'Update Excluding Images' setting when configuring their options for IMPress Listings and how listings are imported and updated. 
Prior to this PR, the 'update-noimage' is the string used by the plugin to verify whether 'Update Excluding Images' has been set. This results in the setting being effectively ignored with images continuing to be updated even when it is set by the user.
Import a supplemental listing with an image into IMPress, update its image within the test IDX Broker account, and then update listings within IMPress again and note that the image will always update even if 'Update Excluding Images' is set.
Then apply the fix and perform …

IMPB-1518  IMPress plugin ignoring update-excluding-images setting

---

idx/views/lead-management.php

Fixed an error with str_contains($string, $string). If we were able to successfully add the lead then the $decoded_response would be an array.

IMPB-1499: Fixed error for string expectation
